---
fail_fast: false
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.35.1"
    hooks:
      - id: yamllint
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 39.171.1
    hooks:
      - id: renovate-config-validator
        files: ^renovate(?:-config)?\.json$
        args: [--strict]
